typography_spectrum: 0.48849
color:
  brandColors:
    - '#ffffff'
    - '#053797'
    - '#000000'
    - '#4865ac'
    - '#ff0000'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75418
analytics:
  google: null
  facebook: null
  twitter: null
name: LNDE
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5dc38ee-fd42-4a5c-a43a-77f91d566235.ico
title: European Federation Lesch-Nyhan Disease
purpose: []
