name: LNDE
favicon: null
layout_spectrum: 0.00941
typography_spectrum: 0.76046
title: LNDE - European Federation Lesch-Nyhan Disease
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#003399'
    - '#000000'
    - '#ffcc00'
    - '#4663ae'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
