typography_spectrum: 0.48849
color:
  brandColors:
    - '#ffffff'
    - '#053797'
    - '#000000'
    - '#4865ac'
    - '#ff0000'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75418
analytics:
  google: null
  facebook: null
  twitter: null
name: LNDE
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 1284b980-09bc-4ec1-a781-f55d323b31aa
    type: content
  - name: Members
    id: d73a05a0-b7a9-4157-9cf0-9874baad08bc
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5dc38ee-fd42-4a5c-a43a-77f91d566235.ico
title: European Federation Lesch-Nyhan Disease
purpose: []
